<?php

namespace AppBundle\Repository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository
{

    public function getAllCategories(){
        $conn = $this->getEntityManager()->getConnection();
        $query = "SELECT
                      DISTINCT(nombre)
                  FROM 
                      category";

        $stmt = $conn->prepare($query);

        $stmt->execute();
        return $stmt->fetchAll();
    }
}
